project:
  type: website
  output-dir: docs

website:
  title: "Simran's Personal Website"
  site-url: https://simb2.github.io/
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: pages/CV/experience.qmd
        text: "Education & Experience"
      - href: pages/CV/projects.qmd
        text: "Projects"
      - href: pages/Interests/readings.qmd
        text: "Readings"
      #- href: pages/Interests/other_interests.qmd
      #  text: "Other Hobbies"
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual