project:
  type: website

website:
  title: "simb2.github.io"
  navbar:
    left:
      - href: index.html
        text: Home
      - about.html

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual