---
title: "Education & Relevant Work Experience"
format: html
---

## Education

------------------------------------------------------------------------

#### McMaster University — Master's in Statistics

*McMaster University* \| *Sept 2024 (Ongoing)*\
**CGPA:** 11.87/12

#### University of Toronto — H.B.Sc. in Applied Statistics

*Minor in Mathematics*\
*Sept 2018 – Apr 2024*\
**CGPA** (final 2 yrs - 10.5 out of 20.5 total credits): 3.76/4.00

------------------------------------------------------------------------

## Work Experience

#### Teaching Assistant — Intermediate Probability Theory

*McMaster University* \| *September 2025 – December 2025*\
- Graded at assessments (tests, assignments, and exams)
- Provided additional support 4 days/week at the Math Help Center to assist first-year students with topics including calculus, proofs,
and linear algebra

#### Teaching Assistant — Statistical Methods with Applications

*McMaster University* \| *January 2025 – April 2025*\
- Led exam review sessions and explained statistical concepts to students\
- Guided practice problem walkthroughs and clarified solutions\
- Provided one-on-one assistance during office hours

#### Teaching Assistant — Linear Regression Models Using SAS

*McMaster University* \| *September 2024 – December 2024*\
- Delivered lab tutorials and guided students through hands-on examples using SAS for linear regression analysis\
- Oversaw and evaluated online course discussions, providing constructive feedback on interpretations, and best practices for report writing\
- Assisted in grading assignments and projects\
- Provided technical support for students struggling with coding issues

#### Student Intern — IT & Data Operations
*Sodexo* \| *May 2020 – Aug 2022*\
- Served as Technical SME for transitioning cloud backup solutions, resulting in operational savings over $50,000\
- Led tracking and replacement of point-of-sale terminals Canada-wide\
- Analyzed telecom contract cost data to identify opportunities for reducing operational expenses\
- Managed data backup project for Canadian employees\
- Oversaw IT equipment asset management, improving sustainability efforts and enabling charitable contributions to the Stop Hunger Foundation\
- Provided field and help desk support\
- Applied data visualization skills to produce project reports for leadership\

